language: java

git:
  quiet: true
  submodules: false

jdk:
  - openjdk8
  - openjdk11

# whitelist
branches:
  only:
    - master
    - "2.11"

# Below this line is configuration for deploying to the Sonatype OSS repo
# https://knowm.org/configure-travis-ci-to-deploy-snapshots/
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings target/travis/settings.xml || mvn clean verify --settings target/travis/settings.xml"

# And generate tokens with
#
# travis encrypt -r FasterXML/jackson-dataformats-binary "CI_DEPLOY_USERNAME=[username]"
# travis encrypt -r FasterXML/jackson-dataformats-binary "CI_DEPLOY_PASSWORD=[password]"
#
# Generated: 2020-09-04

env:
  global:
    - secure: "AtgrURLx7jcAfOn8YVf+lU6asSPWaRW7ZPQjaCURV2U9ZlvlRfB6ueiQbiTnNjoPmfhv7SRtjniYYbuJrzVcSJsinLiVYNVKrHwj/LfV7ps3kn5752/bMyhGxoY95RSYRKct6KSZGqTSyRKuQ6o+y805Vn9l8vLLpcOs32/9yYJ/VEmldzfCvsPJRge/DvB/4aa3O0s50+WLRfu2uQ9a17bQBg3aZScyFiyI/HZcMrwVJRNpD65DYjlrbHPDxmsC2sLV6jsk6wYkf8OTgjH/g/pfhtxBu8RaCi8Y6hX9X/W+iAdXV3Zkie61Hi4XpNOUIM6v6YxGb6XLg9VUl15hnSP7ghM0cyuukmCM0apdOYS+1Iy9didFhQD8JbzkTFQ3XvXgq4pCv+A7RObId/wVdnb/trk5OgKIOs7bvFrBXn/lP6pSYs0A+DYj3GyKnQrGR7WIcRL4WET4HSqotPkd0HqeWeFZnvGh5oYwXhsolUO4272tBvKxSxH3QPArEM6lyrXcXs9ur4kD5h0DHm3AuqK/X/fpNFn/2xzVwnXe7qNRiNyT+OsculSfuKfY8FgbE0w4hxdtyUdMM3/XMT+8ZbKYDBE0ma693ZmW29vRn0wwIdpXCwDuWjCmvEJs5I7PcI/tbnXd/FcfAXOFOVqA3H6+4ujc/m7J8rHgtBTgn+M="
    - secure: "cTkhpI4u8Z5kRvJvjDaESJz2TfruqzfglsdWH5nrwSQUYwqAatDAGwsRGqSBwwf6Nbe1zZ2e/alRSzWif51LPmOm72uzzapGDuy4+2ViAayU+LeOkbUUPg84UqiMcFzh15A72j/NgCRhS+jrPPOagpXm73IxOJjDSKXGl0upldTsCE63SkVJq3ysm81n8qOXYhUGLKDGHvisqHu7i/s26Dt7Q2I/qq8EwA0KcqG6IGkVOkpt15/p6+8gjpC2m4VRRMVvrID4FYEREX+/g0T1JyxtKLo/INeGTd4+gQKcl21d8ZZlhZTKPVKPYNuLhXhnJsraCTjODW+hiaPI56QxgJx8HdSFBCjp/hgJK7J7dFI7/PQaIdufH8/pu1c875UG1S2peoj5Qfzg9e7kT7V4X4jMR9q9PEKYyRY+DLEQbzUe/JjJGhlit+9yq0Mk1xymf40O10eR1AiYb04XvLv/hrB3USSzsLqbCH3jr7aY9bzE7SsabJ89BEHFOu164AlDwNbE7HKao6zQgV8Dd4F46JQOGkcM55+qDsTTxT47qf43rOxL+wkZgkCd6NqnxZyUR7v6BfHY5azd3WffE0SkyBOXFzHbEWCUF5+WxbrOYKyirSWAJmH4mqBi4XJba8jNQVk5JZeJNJLnWBBqXUy2B9GpIANp1SbBBUty5JsljSM="
